# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\JACP\OneDrive - Universidad Nacional de Colombia\Primer Semestre\Programacion Basica\Proyecto\ventanaCodigo.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(350, 400)
        Dialog.setMinimumSize(QtCore.QSize(350, 400))
        Dialog.setMaximumSize(QtCore.QSize(350, 400))
        Dialog.setSizeGripEnabled(False)
        self.btnCalcular = QtWidgets.QPushButton(Dialog)
        self.btnCalcular.setGeometry(QtCore.QRect(40, 350, 81, 31))
        self.btnCalcular.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCalcular.setStyleSheet("")
        self.btnCalcular.setObjectName("btnCalcular")
        self.lblResultado = QtWidgets.QLabel(Dialog)
        self.lblResultado.setGeometry(QtCore.QRect(130, 350, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblResultado.setFont(font)
        self.lblResultado.setText("")
        self.lblResultado.setAlignment(QtCore.Qt.AlignCenter)
        self.lblResultado.setObjectName("lblResultado")
        self.btnBlack = QtWidgets.QPushButton(Dialog)
        self.btnBlack.setGeometry(QtCore.QRect(200, 120, 31, 31))
        self.btnBlack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBlack.setStyleSheet("background-color:\'black\'")
        self.btnBlack.setText("")
        self.btnBlack.setObjectName("btnBlack")
        self.btnBrown = QtWidgets.QPushButton(Dialog)
        self.btnBrown.setGeometry(QtCore.QRect(240, 120, 31, 31))
        self.btnBrown.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBrown.setStyleSheet("background-color:\'brown\'")
        self.btnBrown.setText("")
        self.btnBrown.setObjectName("btnBrown")
        self.btnRed = QtWidgets.QPushButton(Dialog)
        self.btnRed.setGeometry(QtCore.QRect(280, 120, 31, 31))
        self.btnRed.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRed.setStyleSheet("background-color:\'red\'")
        self.btnRed.setText("")
        self.btnRed.setObjectName("btnRed")
        self.btnYellow = QtWidgets.QPushButton(Dialog)
        self.btnYellow.setGeometry(QtCore.QRect(240, 160, 31, 31))
        self.btnYellow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnYellow.setStyleSheet("background-color:\'yellow\'")
        self.btnYellow.setText("")
        self.btnYellow.setObjectName("btnYellow")
        self.btnOrange = QtWidgets.QPushButton(Dialog)
        self.btnOrange.setGeometry(QtCore.QRect(200, 160, 31, 31))
        self.btnOrange.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOrange.setStyleSheet("background-color:\'orange\'")
        self.btnOrange.setText("")
        self.btnOrange.setObjectName("btnOrange")
        self.btnGreen = QtWidgets.QPushButton(Dialog)
        self.btnGreen.setGeometry(QtCore.QRect(280, 160, 31, 31))
        self.btnGreen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGreen.setStyleSheet("background-color:\'green\'")
        self.btnGreen.setText("")
        self.btnGreen.setObjectName("btnGreen")
        self.btnPurple = QtWidgets.QPushButton(Dialog)
        self.btnPurple.setGeometry(QtCore.QRect(240, 200, 31, 31))
        self.btnPurple.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPurple.setStyleSheet("background-color:\'purple\'")
        self.btnPurple.setText("")
        self.btnPurple.setObjectName("btnPurple")
        self.btnBlue = QtWidgets.QPushButton(Dialog)
        self.btnBlue.setGeometry(QtCore.QRect(200, 200, 31, 31))
        self.btnBlue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBlue.setStyleSheet("background-color:\'blue\'")
        self.btnBlue.setText("")
        self.btnBlue.setObjectName("btnBlue")
        self.btnGray = QtWidgets.QPushButton(Dialog)
        self.btnGray.setGeometry(QtCore.QRect(280, 200, 31, 31))
        self.btnGray.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGray.setStyleSheet("background-color:\'gray\'")
        self.btnGray.setText("")
        self.btnGray.setObjectName("btnGray")
        self.btnWhite = QtWidgets.QPushButton(Dialog)
        self.btnWhite.setGeometry(QtCore.QRect(200, 240, 31, 31))
        self.btnWhite.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWhite.setStyleSheet("background-color:\'white\'")
        self.btnWhite.setText("")
        self.btnWhite.setObjectName("btnWhite")
        self.btnSilver = QtWidgets.QPushButton(Dialog)
        self.btnSilver.setGeometry(QtCore.QRect(280, 240, 31, 31))
        self.btnSilver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSilver.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(40, 40, 40, 255), stop:0.16 rgba(136, 136, 136, 255), stop:0.225 rgba(166, 166, 166, 255), stop:0.285 rgba(204, 204, 204, 255), stop:0.345 rgba(235, 235, 235, 255), stop:0.415 rgba(245, 245, 245, 255), stop:0.52 rgba(209, 209, 209, 255), stop:0.57 rgba(187, 187, 187, 255), stop:0.635 rgba(168, 168, 168, 255), stop:0.695 rgba(202, 202, 202, 255), stop:0.75 rgba(218, 218, 218, 255), stop:0.815 rgba(208, 208, 208, 255), stop:0.88 rgba(187, 187, 187, 255), stop:0.9375 rgba(137, 137, 137, 255), stop:1 rgba(40, 40, 40, 255))")
        self.btnSilver.setText("")
        self.btnSilver.setObjectName("btnSilver")
        self.btnGold = QtWidgets.QPushButton(Dialog)
        self.btnGold.setGeometry(QtCore.QRect(240, 240, 31, 31))
        self.btnGold.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGold.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(35, 40, 3, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, 51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255))")
        self.btnGold.setText("")
        self.btnGold.setObjectName("btnGold")
        self.btnBanda1 = QtWidgets.QPushButton(Dialog)
        self.btnBanda1.setGeometry(QtCore.QRect(40, 100, 91, 31))
        self.btnBanda1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBanda1.setObjectName("btnBanda1")
        self.btnBanda2 = QtWidgets.QPushButton(Dialog)
        self.btnBanda2.setGeometry(QtCore.QRect(40, 140, 91, 31))
        self.btnBanda2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBanda2.setObjectName("btnBanda2")
        self.btnBanda3 = QtWidgets.QPushButton(Dialog)
        self.btnBanda3.setGeometry(QtCore.QRect(40, 180, 91, 31))
        self.btnBanda3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBanda3.setObjectName("btnBanda3")
        self.btnTolerancia = QtWidgets.QPushButton(Dialog)
        self.btnTolerancia.setGeometry(QtCore.QRect(30, 240, 103, 31))
        self.btnTolerancia.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnTolerancia.setObjectName("btnTolerancia")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(200, 96, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 351, 401))
        self.label_2.setStyleSheet("border-image: url(:/newPrefix/Hexagon-dotted-connect-line-background.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 0, 111, 331))
        self.label_3.setStyleSheet("border-image: url(:/newPrefix/resistencia.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_2.raise_()
        self.btnCalcular.raise_()
        self.lblResultado.raise_()
        self.btnBlack.raise_()
        self.btnBrown.raise_()
        self.btnRed.raise_()
        self.btnYellow.raise_()
        self.btnOrange.raise_()
        self.btnGreen.raise_()
        self.btnPurple.raise_()
        self.btnBlue.raise_()
        self.btnGray.raise_()
        self.btnWhite.raise_()
        self.btnSilver.raise_()
        self.btnGold.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.btnBanda1.raise_()
        self.btnBanda2.raise_()
        self.btnBanda3.raise_()
        self.btnTolerancia.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Codigo de Colores"))
        self.btnCalcular.setText(_translate("Dialog", "Calcular"))
        self.btnBanda1.setText(_translate("Dialog", "Banda 1"))
        self.btnBanda2.setText(_translate("Dialog", "Banda 2"))
        self.btnBanda3.setText(_translate("Dialog", "Banda 3"))
        self.btnTolerancia.setText(_translate("Dialog", "Tolerancia"))
        self.label.setText(_translate("Dialog", "Colores"))
import imagesColores_rc
